### ISSUE TITLE
a.getScript(...).success is not a function

### ISSUE THREAD

**Issue by clementduveau** [sdepold/jquery.google-search#1]
Hi,

jquery.google-search.min.js contains an error. The callback using "success" method is not working.

Your library is really interesting. I may be contributing when I have time.

**Comment by Liam-DeVoe** [comment]
Try using the provided jquery version in the repository (1.7.2 as of now). This solved the issue for me.

**Comment by clementduveau** [comment]
Cleaning up 😅
